<?php
/**
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var \Licentia\Equity\Block\TwoFactor $block */

?>
<style type="text/css">
    .container {
        width: 450px;
        height: 35vh;
        margin: 20px auto;
    }

    img {
        padding: 50px 0;
    }
</style>

<div class="container">
    <img src="<?= $block->escapeHtmlAttr($block->getLogoSrc()) ?>"
         alt="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"/>
    <?php if ($block->hasCellphone()) : ?>
        <form class=" form form-twofactor-manage" data-mage-init='{"validation":{}}'
              action="<?= /* @noEscape */
              $block->getUrl('pandae/twofactor/save') ?>" method="post"
              id="form-validate">
            <fieldset class="fieldset">
                <?= $block->getBlockHtml('formkey') ?>
                <legend class="legend"><span><?= /* @noEscape */
                        __('Two-Factor Authentication Required') ?></span>
                </legend>
                <br>

                <div class="field choice">
                    <input type="text" name="sms_code" data-validate="{required:true}" id="sms_code">
                    <label for="subscription" class="label"> <span><?= /* @noEscape */
                            __(
                                'Please insert the SMS code you received'
                            ) ?></span>
                    </label>
                </div>
                <?php if ($block->getAllowRemember()): ?>
                    <div class="field choice">
                        <input type="checkbox" name="sms_remember_browser" id="sms_remember_browser">
                        <label for="sms_remember_browser" class="label"> <span><?= /* @noEscape */
                                __(
                                    'Do not ask again for this browser for the next %1 days',
                                    $block->getDaysToRemember()
                                ) ?></span>
                        </label>
                    </div>
                <?php endif; ?>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" title="<?= $block->escapeHtmlAttr(__('Continue')) ?>"
                            class="action save primary">
                        <span><?= /* @noEscape */
                            __('Continue') ?></span>
                    </button>
                </div>
                <?php if ($block->canGenerateCode()): ?>
                    <div class="secondary">
                        <a href="<?= /* @noEscape */
                        $block->getUrl('pandae/twofactor/auth', ['resend' => 1]) ?>"
                           title="<?= $block->escapeHtmlAttr(__('Resend SMS')) ?>" class="action  secondary">
                            <span><?= /* @noEscape */
                                __('Resend SMS') ?></span>
                        </a>
                    </div>
                <?php endif; ?>
            </div>
            <div class="actions-toolbar">
                <div class="secondary" style="float: right;">
                    <a href="<?= /* @noEscape */
                    $block->getUrl('customer/account/logout', []) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Logout')) ?>" class="action  secondary">
                        <span><?= /* @noEscape */
                            __('Logout') ?></span>
                    </a>
                </div>
            </div>
        </form>
    <?php endif; ?>
    <?php if (!$block->hasCellphone()): ?>
        <form class="form form-twofactor-manage" data-mage-init='{"validation":{}}'
              action="<?= /* @noEscape */
              $block->getUrl('pandae/twofactor/save') ?>" method="post"
              id="form-validate">
            <fieldset class="fieldset">
                <?= /* @noEscape */
                $block->getBlockHtml('formkey') ?>
                <legend class="legend"><span><?= /* @noEscape */
                        __('Two-Factor Authentication Required') ?></span>
                </legend>
                <div class="field choice">
                    <label for="subscription" class="label"> <span><?= /* @noEscape */
                            __(
                                'Please insert your cellphone number. This number will only be used to send Auth Codes'
                            ) ?></span>
                    </label>
                    <input type="text" name="cellphone" data-validate="{required:true}" id="cellphone">
                    <small><em><?= /* @noEscape */
                            __(
                                'Please use the following format: CountryCode-CellPhoneNumber. <br>Ex: 351-989647542'
                            ) ?></em></small>
                </div>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" title="<?= /* @noEscape */
                    __('Update Cellphone') ?>"
                            class="action save primary">
                        <span><?= /* @noEscape */
                            __('Update Cellphone') ?></span>
                    </button>
                </div>
            </div>
            <div class="actions-toolbar">
                <div class="secondary" style="float: right;">
                    <a href="<?= /* @noEscape */
                    $block->getUrl('customer/account/logout', []) ?>"
                       title="<?= /* @noEscape */
                       __('Logout') ?>" class="action secondary">
                    <span><?= /* @noEscape */
                        __('Logout') ?></span>
                    </a>
                </div>
            </div>
        </form>
    <?php endif; ?>
</div>